# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b179e921286b421aee4fe17a645f52c199f2dceb722aaa873708c8990af9e6ab574045403b769872e578968cff10bdfc4566326d45ceebb5be74df2510e98767

test:
  secret_key_base: 5449c189cca2f1275bbcd8d269eed706270eb251d3dfde53b33cbe6f5d8706bc9b4c4eb467b9ecef6de30e134239523eb7024aca73f3728f7ff385ffda6f2ee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
